/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.called2;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Called2 extends AbstractCalled2 { 
	public Called2(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
