/* Generated by AN DISI Unibo */ 
package it.unibo.qa0

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Qa0 ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("qa0 STARTS")
						forward("cmd", "cmd(hello_from_myself)" ,"qa0" ) 
					}
					 transition(edgeName="t00",targetState="handleAlarm",cond=whenEvent("alarm"))
					transition(edgeName="t01",targetState="handleMsg",cond=whenDispatch("cmd"))
				}	 
				state("handleAlarm") { //this:State
					action { //it:State
						updateResourceRep( "handlealarm"  
						)
						println("$name in ${currentState.stateName} | $currentMsg")
					}
					 transition(edgeName="t02",targetState="handleAlarm",cond=whenEvent("alarm"))
					transition(edgeName="t03",targetState="handleMsg",cond=whenDispatch("cmd"))
				}	 
				state("handleMsg") { //this:State
					action { //it:State
						updateResourceRep( "handleMsg"  
						)
						println("$name in ${currentState.stateName} | $currentMsg")
						emit("alarm", "alarm(fire)" ) 
					}
					 transition(edgeName="t04",targetState="handleAlarm",cond=whenEvent("alarm"))
					transition(edgeName="t05",targetState="handleMsg",cond=whenDispatch("cmd"))
				}	 
			}
		}
}
