/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.consumer2distrmqtt;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Consumer2distrmqtt extends AbstractConsumer2distrmqtt { 
	public Consumer2distrmqtt(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
