/* Generated by AN DISI Unibo */ 
package it.unibo.called1;
import it.unibo.qactors.PlanRepeat;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.StateExecMessage;
import it.unibo.qactors.QActorUtils;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.akka.QActor;
import it.unibo.qactors.StateFun;
import java.util.Stack;
import java.util.Hashtable;
import java.util.concurrent.Callable;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.action.ActorTimedAction;
public abstract class AbstractCalled1 extends QActor { 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	protected String planFilePath    = null;
	protected String terminationEvId = "default";
	protected String parg="";
	protected boolean bres=false;
	protected IActorAction action;
	//protected String mqttServer = "";
	
		protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
			return outEnvView;
		}
		public AbstractCalled1(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx,  
			"./srcMore/it/unibo/called1/WorldTheory.pl",
			setTheEnv( outEnvView )  , "init");
			this.planFilePath = "./srcMore/it/unibo/called1/plans.txt";
	  	}
		@Override
		protected void doJob() throws Exception {
			String name  = getName().replace("_ctrl", "");
			mysupport = (IMsgQueue) QActorUtils.getQActor( name ); 
			initStateTable(); 
	 		initSensorSystem();
	 		history.push(stateTab.get( "init" ));
	  	 	autoSendStateExecMsg();
	  		//QActorContext.terminateQActorSystem(this);//todo
		} 	
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/    
	    //genAkkaMshHandleStructure
	    protected void initStateTable(){  	
	    	stateTab.put("handleToutBuiltIn",handleToutBuiltIn);
	    	stateTab.put("init",init);
	    	stateTab.put("waitRequest",waitRequest);
	    	stateTab.put("handleRequest",handleRequest);
	    	stateTab.put("handleSecondRequest",handleSecondRequest);
	    	stateTab.put("sendAnswerToCaller",sendAnswerToCaller);
	    }
	    StateFun handleToutBuiltIn = () -> {	
	    	try{	
	    		PlanRepeat pr = PlanRepeat.setUp("handleTout",-1);
	    		String myselfName = "handleToutBuiltIn";  
	    		println( "called1 tout : stops");  
	    		repeatPlanNoTransition(pr,myselfName,"application_"+myselfName,false,false);
	    	}catch(Exception e_handleToutBuiltIn){  
	    		println( getName() + " plan=handleToutBuiltIn WARNING:" + e_handleToutBuiltIn.getMessage() );
	    		QActorContext.terminateQActorSystem(this); 
	    	}
	    };//handleToutBuiltIn
	    
	    StateFun init = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("init",-1);
	    	String myselfName = "init";  
	    	temporaryStr = "\"called1 STARTS\"";
	    	println( temporaryStr );  
	    	//switchTo waitRequest
	        switchToPlanAsNextState(pr, myselfName, "called1_"+myselfName, 
	              "waitRequest",false, false, null); 
	    }catch(Exception e_init){  
	    	 println( getName() + " plan=init WARNING:" + e_init.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//init
	    
	    StateFun waitRequest = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("waitRequest",-1);
	    	String myselfName = "waitRequest";  
	    	temporaryStr = "\"called1 waiting ...\"";
	    	println( temporaryStr );  
	    	//bbb
	     msgTransition( pr,myselfName,"called1_"+myselfName,false,
	          new StateFun[]{stateTab.get("handleRequest") }, 
	          new String[]{"true","M","arequest" },
	          5000, "handleToutBuiltIn" );//msgTransition
	    }catch(Exception e_waitRequest){  
	    	 println( getName() + " plan=waitRequest WARNING:" + e_waitRequest.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//waitRequest
	    
	    StateFun handleRequest = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("handleRequest",-1);
	    	String myselfName = "handleRequest";  
	    	printCurrentMessage(false);
	    	storeCurrentMessageForReply();
	    	//onMsg 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("arequest(r1,DD)");
	    	if( currentMessage != null && currentMessage.msgId().equals("arequest") && 
	    		pengine.unify(curT, Term.createTerm("arequest(REQUEST,DATA)")) && 
	    		pengine.unify(curT, Term.createTerm( currentMessage.msgContent() ) )){ 
	    		String parg="answer(called1(r1),D)";
	    		/* ReplyToCaller */
	    		parg = updateVars( Term.createTerm("arequest(REQUEST,DATA)"),  Term.createTerm("arequest(r1,DD)"), 
	    			    		  					Term.createTerm(currentMessage.msgContent()), parg);
	    		if( parg != null ) replyToCaller("answer", parg);
	    	}
	    	//onMsg 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("arequest(r2,D)");
	    	if( currentMessage != null && currentMessage.msgId().equals("arequest") && 
	    		pengine.unify(curT, Term.createTerm("arequest(REQUEST,DATA)")) && 
	    		pengine.unify(curT, Term.createTerm( currentMessage.msgContent() ) )){ 
	    		String parg="autoMsg(arequest(r2,D))";
	    		/* SendDispatch */
	    		parg = updateVars(Term.createTerm("arequest(REQUEST,DATA)"),  Term.createTerm("arequest(r2,D)"), 
	    			    		  					Term.createTerm(currentMessage.msgContent()), parg);
	    		if( parg != null ) sendMsg("autoMsg",getNameNoCtrl(), QActorContext.dispatch, parg ); 
	    	}
	    	//bbb
	     msgTransition( pr,myselfName,"called1_"+myselfName,false,
	          new StateFun[]{stateTab.get("handleSecondRequest") }, 
	          new String[]{"true","M","autoMsg" },
	          500, "waitRequest" );//msgTransition
	    }catch(Exception e_handleRequest){  
	    	 println( getName() + " plan=handleRequest WARNING:" + e_handleRequest.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//handleRequest
	    
	    StateFun handleSecondRequest = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("handleSecondRequest",-1);
	    	String myselfName = "handleSecondRequest";  
	    	temporaryStr = "\"called1 handleSecondRequest \"";
	    	println( temporaryStr );  
	    	//onMsg 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("autoMsg(M)");
	    	if( currentMessage != null && currentMessage.msgId().equals("autoMsg") && 
	    		pengine.unify(curT, Term.createTerm("autoMsg(X)")) && 
	    		pengine.unify(curT, Term.createTerm( currentMessage.msgContent() ) )){ 
	    		String parg="M";
	    		/* SendDispatch */
	    		parg = updateVars(Term.createTerm("autoMsg(X)"),  Term.createTerm("autoMsg(M)"), 
	    			    		  					Term.createTerm(currentMessage.msgContent()), parg);
	    		if( parg != null ) sendMsg("arequest","called2", QActorContext.dispatch, parg ); 
	    	}
	    	//bbb
	     msgTransition( pr,myselfName,"called1_"+myselfName,false,
	          new StateFun[]{stateTab.get("sendAnswerToCaller") }, 
	          new String[]{"true","M","answer" },
	          5000, "handleToutBuiltIn" );//msgTransition
	    }catch(Exception e_handleSecondRequest){  
	    	 println( getName() + " plan=handleSecondRequest WARNING:" + e_handleSecondRequest.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//handleSecondRequest
	    
	    StateFun sendAnswerToCaller = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("sendAnswerToCaller",-1);
	    	String myselfName = "sendAnswerToCaller";  
	    	temporaryStr = "\"called1 send the answer from called2 to its original caller \"";
	    	println( temporaryStr );  
	    	printCurrentMessage(false);
	    	//onMsg 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("answer(R,D)");
	    	if( currentMessage != null && currentMessage.msgId().equals("answer") && 
	    		pengine.unify(curT, Term.createTerm("answer(REQUEST,DATA)")) && 
	    		pengine.unify(curT, Term.createTerm( currentMessage.msgContent() ) )){ 
	    		String parg="answer(called1(R),D)";
	    		/* ReplyToCaller */
	    		parg = updateVars( Term.createTerm("answer(REQUEST,DATA)"),  Term.createTerm("answer(R,D)"), 
	    			    		  					Term.createTerm(currentMessage.msgContent()), parg);
	    		if( parg != null ) replyToCaller("answer", parg);
	    	}
	    	//bbb
	     msgTransition( pr,myselfName,"called1_"+myselfName,false,
	          new StateFun[]{}, 
	          new String[]{},
	          3000, "handleToutBuiltIn" );//msgTransition
	    }catch(Exception e_sendAnswerToCaller){  
	    	 println( getName() + " plan=sendAnswerToCaller WARNING:" + e_sendAnswerToCaller.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//sendAnswerToCaller
	    
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	
	}
